name: LaravelChronos
on: [push, pull_request]
jobs:
  laravel:
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: password
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [7.2, 7.3, 7.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run tests
        run: vendor/bin/phpunit tests/
